#include "GOOFNameGenerator.h"
#include <sstream>

namespace GOOF
{
    const std::string DEFAULT_NAME_PREFIX = "AutoGeneratedName";
    NameGenerator::NameCountMap NameGenerator::s_nameCount;
    
    NameGenerator::NameGenerator(void)
    {
    }
    
    NameGenerator::~NameGenerator(void)
    {
    }
    
    std::string NameGenerator::Next()
    {
        return Next(DEFAULT_NAME_PREFIX);
    }
    
    std::string NameGenerator::Next( const std::string& prefix )
    {
        if (s_nameCount.count(prefix) == 0)
        {
            s_nameCount[prefix] = 0;
        }
        std::stringstream ss;
        ss << prefix << "_" << s_nameCount[prefix]++;
        return ss.str();
    }
    
    size_t NameGenerator::Count()
    {
        size_t count = Count(DEFAULT_NAME_PREFIX);
        return count;
    }
    
    size_t NameGenerator::Count( const std::string& prefix )
    {
        size_t count = (s_nameCount.count(prefix) == 0) ? 0 : s_nameCount[prefix];
        return count;
    }
}